[corpus]
id = "closedxml"
name = "ClosedXML"
path = "corpus/ClosedXML"
license = "MIT"
source = "https://github.com/ClosedXML/ClosedXML"
source_commit = "4e89dcedd83cad553e84d2d97f77fc3d7deb630f"
default_roundtrip = false
