use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let workspace = crate_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace layout");
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    generate(
        workspace,
        &out,
        "Apache-POI",
        "apache_poi",
        "apache_poi_cfb_tests.rs",
    );
    generate(
        workspace,
        &out,
        "LibreOffice",
        "libreoffice",
        "libreoffice_cfb_tests.rs",
    );
}

fn generate(workspace: &Path, out: &Path, corpus: &str, prefix: &str, output: &str) {
    let root = workspace.join("corpus").join(corpus);
    let manifest_path = root.join("manifest.toml");
    println!("cargo:rerun-if-changed={}", root.display());
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let expectations = expectations(&manifest_path, &root, corpus);
    let mut files = Vec::new();
    collect(&root, workspace, &mut files);
    files.sort();

    let mut generated = String::from("// @generated by build.rs\n\n");
    let mut slugs = BTreeMap::new();
    for file in files {
        let base = slugify(&file);
        let count = slugs.entry(base.clone()).or_insert(0usize);
        *count += 1;
        let slug = if *count == 1 {
            base
        } else {
            format!("{base}_{}", *count)
        };
        let mode = expectations.get(&file).copied().unwrap_or(Mode::RoundTrip);
        let (name, assertion, ignore) = match mode {
            Mode::RoundTrip => (
                "round_trip",
                "assert_cfb_round_trip",
                "CFB corpus round-trip tests run explicitly",
            ),
            Mode::OpenOnly | Mode::RequiresPassword => (
                "open_only",
                "assert_cfb_opens",
                "CFB corpus open-only tests run explicitly",
            ),
            Mode::Invalid => (
                "invalid",
                "assert_cfb_rejected",
                "CFB invalid corpus tests run explicitly",
            ),
            Mode::Unsupported => (
                "unsupported",
                "assert_cfb_unsupported",
                "non-CFB legacy corpus tests run explicitly",
            ),
            Mode::KnownFailure => (
                "known_failure",
                "assert_cfb_round_trip",
                "known CFB corpus failure",
            ),
        };
        generated.push_str(&format!(
            "#[test]\n#[ignore = {ignore:?}]\nfn {name}_{prefix}_{slug}() {{\n    let path = olecfsdk_corpus_test_support::corpus_file_path({file:?});\n    olecfsdk_corpus_test_support::{assertion}(&path, {file:?});\n}}\n\n"
        ));
    }
    fs::write(out.join(output), generated).expect("write generated CFB tests");
}

fn collect(dir: &Path, workspace: &Path, files: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read corpus") {
        let entry = entry.expect("read entry");
        let path = entry.path();
        if path.is_dir() {
            collect(&path, workspace, files);
        } else if is_binary_office(&path) {
            files.push(
                path.strip_prefix(workspace.join("corpus"))
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn is_binary_office(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| {
            matches!(
                ext.to_ascii_lowercase().as_str(),
                "doc" | "dot" | "xls" | "xlt" | "ppt" | "pps" | "pot"
            )
        })
}

#[derive(Deserialize)]
struct Manifest {
    #[serde(default)]
    expectation: Vec<Expectation>,
}
#[derive(Deserialize)]
struct Expectation {
    file: String,
    test: String,
    mode: Mode,
    reason: String,
}
#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Mode {
    RoundTrip,
    OpenOnly,
    Invalid,
    Unsupported,
    RequiresPassword,
    KnownFailure,
}

fn expectations(path: &Path, root: &Path, corpus: &str) -> BTreeMap<String, Mode> {
    let raw = fs::read_to_string(path).expect("read corpus manifest");
    let manifest: Manifest = toml::from_str(&raw).expect("parse corpus manifest");
    let mut result = BTreeMap::new();
    for item in manifest
        .expectation
        .into_iter()
        .filter(|item| item.test == "cfb_roundtrip")
    {
        assert!(
            !item.reason.trim().is_empty(),
            "empty cfb_roundtrip reason for {corpus}/{}",
            item.file
        );
        let relative = Path::new(&item.file);
        assert!(
            relative.is_relative()
                && relative
                    .components()
                    .all(|part| !matches!(part, std::path::Component::ParentDir)),
            "cfb_roundtrip manifest path escapes corpus: {corpus}/{}",
            item.file
        );
        let fixture = root.join(relative);
        assert!(
            fixture.is_file(),
            "cfb_roundtrip manifest fixture does not exist: {corpus}/{}",
            item.file
        );
        assert!(
            is_binary_office(&fixture),
            "cfb_roundtrip manifest fixture has an unsupported extension: {corpus}/{}",
            item.file
        );
        let file = format!("{corpus}/{}", item.file);
        assert!(
            result.insert(file.clone(), item.mode).is_none(),
            "duplicate cfb_roundtrip manifest entry: {file}"
        );
    }
    result
}

fn slugify(input: &str) -> String {
    let mut out = String::new();
    let mut underscore = false;
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            underscore = false;
        } else if !underscore {
            out.push('_');
            underscore = true;
        }
    }
    let mut out = out.trim_matches('_').to_string();
    if out.is_empty() {
        out.push_str("sample");
    }
    if out.starts_with(|ch: char| ch.is_ascii_digit()) {
        out.insert_str(0, "sample_");
    }
    out
}
