use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let workspace_dir = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("test crate should be under crates/");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));

    println!(
        "cargo:rerun-if-changed={}",
        workspace_dir.join("corpus-manifest.toml").display()
    );

    generate_corpus_tests(
        workspace_dir,
        &out_dir,
        CorpusConfig {
            dir_name: "Open-XML-SDK",
            fn_prefix: "open_xml_sdk",
            out_file: "open_xml_sdk_roundtrip_tests.rs",
        },
    );
    generate_corpus_tests(
        workspace_dir,
        &out_dir,
        CorpusConfig {
            dir_name: "Apache-POI",
            fn_prefix: "apache_poi",
            out_file: "apache_poi_roundtrip_tests.rs",
        },
    );
    generate_corpus_tests(
        workspace_dir,
        &out_dir,
        CorpusConfig {
            dir_name: "LibreOffice",
            fn_prefix: "libreoffice",
            out_file: "libreoffice_roundtrip_tests.rs",
        },
    );
}

#[derive(Clone, Copy)]
struct CorpusConfig {
    dir_name: &'static str,
    fn_prefix: &'static str,
    out_file: &'static str,
}

fn generate_corpus_tests(workspace_dir: &Path, out_dir: &Path, config: CorpusConfig) {
    let corpus_dir = workspace_dir.join("corpus").join(config.dir_name);
    let out_file = out_dir.join(config.out_file);

    println!("cargo:rerun-if-changed={}", corpus_dir.display());
    println!(
        "cargo:rerun-if-changed={}",
        corpus_dir.join("manifest.toml").display()
    );

    let expectations = read_expectations(&corpus_dir.join("manifest.toml"), config.dir_name);
    let mut files = collect_doc_files(&corpus_dir, workspace_dir);
    files.sort();

    let mut generated = String::from("// @generated by build.rs\n\n");
    let mut slug_counts = BTreeMap::new();
    for file_name in files {
        let slug_base = slugify(&file_name);
        let count = slug_counts.entry(slug_base.clone()).or_insert(0);
        *count += 1;
        let slug = if *count == 1 {
            slug_base
        } else {
            format!("{slug_base}_{}", *count)
        };
        match expectations.get(&file_name).copied().unwrap_or(ExpectationMode::RoundTrip) {
      ExpectationMode::RoundTrip => generated.push_str(&format!(
        "#[test]\n#[ignore = \"corpus round-trip tests are run explicitly\"]\nfn round_trip_{}_{slug}() {{\n  let path = ooxmlsdk_corpus_test_support::corpus_file_path({file_name:?});\n  ooxmlsdk_corpus_test_support::roundtrip::assert_package_file_round_trip(&path, {file_name:?});\n}}\n\n",
        config.fn_prefix
      )),
      ExpectationMode::OpenOnly => generated.push_str(&format!(
        "#[test]\n#[ignore = \"corpus open-only tests are run explicitly\"]\nfn open_only_{}_{slug}() {{\n  let path = ooxmlsdk_corpus_test_support::corpus_file_path({file_name:?});\n  ooxmlsdk_corpus_test_support::roundtrip::assert_package_file_opens(&path, {file_name:?});\n}}\n\n",
        config.fn_prefix
      )),
      ExpectationMode::Invalid => generated.push_str(&format!(
        "#[test]\n#[ignore = \"corpus invalid-package tests are run explicitly\"]\nfn invalid_{}_{slug}() {{\n  let path = ooxmlsdk_corpus_test_support::corpus_file_path({file_name:?});\n  ooxmlsdk_corpus_test_support::roundtrip::assert_package_file_invalid(&path, {file_name:?});\n}}\n\n",
        config.fn_prefix
      )),
      ExpectationMode::Unsupported | ExpectationMode::RequiresPassword => {
        panic!("OOXML roundtrip expectations do not support unsupported or requires_password for {file_name}")
      }
      ExpectationMode::KnownFailure => generated.push_str(&format!(
        "#[test]\n#[ignore = \"known corpus failure\"]\nfn known_failure_{}_{slug}() {{\n  let path = ooxmlsdk_corpus_test_support::corpus_file_path({file_name:?});\n  ooxmlsdk_corpus_test_support::roundtrip::assert_package_file_round_trip(&path, {file_name:?});\n}}\n\n",
        config.fn_prefix
      )),
    }
    }

    fs::write(&out_file, generated).unwrap_or_else(|err| {
        panic!(
            "write generated {} round-trip tests {}: {err}",
            config.dir_name,
            out_file.display()
        )
    });
}

#[derive(Deserialize)]
struct CorpusManifest {
    #[serde(default)]
    corpus: Option<CorpusEntry>,
    #[serde(default)]
    expectation: Vec<Expectation>,
}

#[derive(Deserialize)]
struct CorpusEntry {
    id: String,
    path: String,
}

#[derive(Deserialize)]
struct Expectation {
    file: String,
    test: String,
    mode: ExpectationMode,
}

#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum ExpectationMode {
    RoundTrip,
    OpenOnly,
    Invalid,
    Unsupported,
    RequiresPassword,
    KnownFailure,
}

fn read_expectations(path: &Path, corpus_dir_name: &str) -> BTreeMap<String, ExpectationMode> {
    if !path.exists() {
        return BTreeMap::new();
    }

    let raw = fs::read_to_string(path).expect("read corpus-manifest.toml");
    let manifest: CorpusManifest = toml::from_str(&raw).expect("parse corpus-manifest.toml");
    if let Some(corpus) = &manifest.corpus {
        let _ = (&corpus.id, &corpus.path);
    }
    manifest
        .expectation
        .into_iter()
        .filter(|expectation| expectation.test == "roundtrip")
        .map(|expectation| {
            (
                format!("{corpus_dir_name}/{}", expectation.file),
                expectation.mode,
            )
        })
        .collect()
}

fn collect_doc_files(root: &Path, workspace_dir: &Path) -> Vec<String> {
    if !root.exists() {
        return Vec::new();
    }

    let mut files = Vec::new();
    collect_doc_files_recursive(root, workspace_dir, &mut files);
    files
}

fn collect_doc_files_recursive(dir: &Path, workspace_dir: &Path, files: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read corpus dir") {
        let entry = entry.expect("read corpus entry");
        let path = entry.path();

        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            collect_doc_files_recursive(&path, workspace_dir, files);
            continue;
        }

        if path.is_file() && is_supported_document_path(&path) {
            println!("cargo:rerun-if-changed={}", path.display());
            files.push(
                path.strip_prefix(workspace_dir.join("corpus"))
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn is_supported_document_path(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| {
            matches!(
                ext.to_ascii_lowercase().as_str(),
                "docx"
                    | "dotx"
                    | "docm"
                    | "dotm"
                    | "xlsx"
                    | "xltx"
                    | "xlsm"
                    | "xltm"
                    | "pptx"
                    | "potx"
                    | "pptm"
                    | "potm"
            )
        })
}

fn slugify(input: &str) -> String {
    let mut out = String::new();
    let mut prev_underscore = false;

    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            prev_underscore = false;
        } else if !prev_underscore {
            out.push('_');
            prev_underscore = true;
        }
    }

    while out.starts_with('_') {
        out.remove(0);
    }
    while out.ends_with('_') {
        out.pop();
    }

    if out.is_empty() {
        out.push_str("sample");
    }
    if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        out.insert_str(0, "sample_");
    }

    out
}
